defaults:
  - dataset: re10k

name: dataset
image_shape: [256, 256]
dataset: 
  image_shape: [256, 256]
  roots: [datasets/re10k]
  near: 0.5
  far: 100.
  baseline_scale_bounds: false
  make_baseline_1: false
  train_times_per_scene: 1
  highres: false