defaults:
  - context_provider: images
  - views_provider: gradio
  - model/encoder: depthsplat
  - model/decoder: splatting_cuda

type: infer




model:
  encoder:
    monodepth_vit_type: vitl
    num_scales: 2
    upsample_factor: 2
    lowest_feature_resolution: 4



    
