defaults:
  - dataset: re10k
  - model/encoder: depthsplat
  - model/decoder: splatting_cuda

type: infer

context_provider:
  name: dataset
  dataset:
    name: re10k
    roots: [datasets/re10k]
    make_baseline_1: false
    augment: true
    image_shape: [480, 640]
    background_color: [0.0, 0.0, 0.0]
    cameras_are_circular: false
    overfit_to_scene: null
    baseline_epsilon: 0.001
    max_fov: 100.0
    skip_bad_shape: true
    near: -1.0
    far: -1.0
    baseline_scale_bounds: true
    shuffle_val: true
    test_len: -1
    test_chunk_interval: 1
    use_index_to_load_chunk: false
    view_sampler:
      name: bounded
      num_target_views: 1
      num_context_views: 2
      min_distance_between_context_views: 2
      max_distance_between_context_views: 6
      min_distance_to_context_views: 0
      warm_up_steps: 0
      initial_min_distance_between_context_views: 2
      initial_max_distance_between_context_views: 6
  image_shape: [256, 256]

