defaults:
  - context_provider: dataset
  - model/encoder: depthsplat
  - model/decoder: splatting_cuda

type: infer




model:
  encoder:
    monodepth_vit_type: vitl
    num_scales: 2
    upsample_factor: 2
    lowest_feature_resolution: 4



    
# dataset: 
#   image_shape: [256, 256]
#   roots: [datasets/re10k]
#   near: 0.5
#   far: 100.
#   baseline_scale_bounds: false
#   make_baseline_1: false
#   train_times_per_scene: 1
#   highres: false

